import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtempSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {WorkflowStore} from './workflow-store.mjs';
import {FlowRuntime,runVisible} from './flow-runtime.mjs';
import {FlowFeishu} from './flow-feishu.mjs';
import {catalog,graphFor,modules} from './flow-catalog.mjs';
import {visible as legacyVisible} from './task-workflow.mjs';
const staff=[{number:'M',name:'主管',center:'A',role:'manager',active:true},{number:'A',name:'制作',center:'A',role:'specialist',active:true},{number:'B',name:'审核',center:'A',role:'specialist',active:true},{number:'X',name:'其他中心',center:'B',role:'manager',active:true}];
const access=(number='M')=>({enabled:true,canManage:staff.find(p=>p.number===number).role==='manager',department:false,modules:Object.values(modules),user:staff.find(p=>p.number===number)});
function fixture(t){const dir=mkdtempSync(join(tmpdir(),'flow-test-'));t.after(()=>rmSync(dir,{recursive:true,force:true}));const store=new WorkflowStore(join(dir,'tasks.json'));let now=Date.parse('2026-09-08T06:00:00Z');return {store,runtime:new FlowRuntime(store,{people:()=>staff,clock:()=>now}),clock:()=>now,advance:ms=>now+=ms};}
const body=(workflow='00',options={})=>({workflow,options,title:'真实事项',sourceUrl:'https://example.com/source',acceptance:'对应任务交付可核验产物',owner:'A',manager:'M',slaHours:1});
const evidence=[{url:'https://example.com/evidence',reference:'work-42',version:'v1'}];
test('待办概览保留普通节点的业务标题和关联编号，不修改原任务',t=>{const {runtime,store}=fixture(t);const task=runtime.create(access(),body(),'inbox-title-001'),before=JSON.stringify(store.read());const overview=runtime.overview(access());const current=overview.tasks.find(x=>x.id===task.id);assert.deepEqual(current.nodes.map(n=>({id:n.id,title:n.title})),task.runtime.nodes.map(n=>({id:n.id,title:n.title})));assert.ok(current.nodes.every(n=>typeof n.title==='string'&&n.title!==n.id));assert.equal(current.version,task.version);assert.equal(JSON.stringify(store.read()),before);});
function done(r,task,node,who=node.owner.number){return r.command(access(who),task.id,'complete',{expectedVersion:task.version,nodeId:node.id,note:'核对原交付并确认',evidence},'finish-'+node.id+'-'+node.attempt,{verifiedEvidence:node.evidenceKind!=='human_attested'?[{...evidence[0],source:'isolated_test_fixture'}]:null});}
test('所有业务图和人事分支没有孤儿、环路或重复节点',()=>{for(const f of catalog.flows){const options=f.id==='01'?[{production:'ai'},{production:'shoot'},{production:'both'}]:f.id==='06'?catalog.stages.filter(s=>s.flow==='06').flatMap(s=>s.id==='W06.S3'?['onboarding','probation','access'].map(branch=>({stage:s.id,branch})):s.id==='W06.S5'?['status','conversation'].map(branch=>({stage:s.id,branch})):s.id==='W06.S6'?['target','review'].map(branch=>({stage:s.id,branch})):[{stage:s.id}]):[{}];for(const opt of options){const nodes=graphFor(f.id,opt),seen=new Set();assert.equal(new Set(nodes.map(n=>n.id)).size,nodes.length);for(let i=0;i<nodes.length;i++)for(const n of nodes)if(n.dependencies.every(k=>seen.has(k)))seen.add(n.id);assert.equal(seen.size,nodes.length,f.id+JSON.stringify(opt));}}});
for(const flow of ['00','01','02','03','04','05','06'])test('流程 '+flow+' 从主责通知到逐节点凭证和完成通知持久化',t=>{const {runtime:r,store}=fixture(t);let task=r.create(access(),body(flow,flow==='01'?{production:'both'}:flow==='06'?{stage:'W06.S4'}:{}),'create-0001');assert.equal(task.notifications[0].recipient,'A');while(task.runtime.state==='running'){const n=task.runtime.nodes.find(n=>n.state==='ready');assert.ok(n);task=done(r,task,n);}assert.equal(task.status,'completed');assert.equal(task.flowEvents.filter(e=>e.action==='node_completed').length,task.runtime.nodes.length);assert.ok(task.notifications.some(n=>n.kind==='completed'&&n.recipient==='M'));assert.equal(new FlowRuntime(store,{people:()=>staff}).get(access(),task.id).runtime.state,'completed');});
test('重复创建、重复办理与旧版本冲突不会重复推进',t=>{const {runtime:r}=fixture(t);const b=body(),task=r.create(access(),b,'create-0001');assert.equal(r.create(access(),b,'create-0001').id,task.id);assert.throws(()=>r.create(access(),{...b,title:'changed'},'create-0001'),e=>e.status===409);const n=task.runtime.nodes[0],result=done(r,task,n);assert.equal(done(r,task,n).version,result.version);assert.throws(()=>r.command(access(),task.id,'complete',{expectedVersion:1,nodeId:result.runtime.nodes[1].id,note:'x',evidence},'new-key-123'),e=>e.status===409);});
test('跨流程交接与结束原子保存，重放或重启不重复派发',t=>{const {runtime:r,store}=fixture(t);let task=r.create(access(),body('00'),'create-0001');const config={...body('02'),expectedVersion:task.version};task=r.configureHandoff(access(),task.id,config,'handoff-001');assert.equal(task.runtime.handoff.draft,undefined);assert.equal(store.read().tasks.length,1);assert.equal(r.configureHandoff(access(),task.id,config,'handoff-001').version,task.version);while(task.runtime.state==='running')task=done(r,task,task.runtime.nodes.find(n=>n.state==='ready'));assert.equal(store.read().tasks.length,2);task=r.get(access(),task.id);const next=r.get(access(),task.runtime.handoff.taskId);assert.equal(next.runtime.parentTaskId,task.id);assert.equal(next.runtime.nodes[0].state,'ready');assert.equal(next.notifications.filter(n=>n.kind==='ready').length,1);assert.equal(new FlowRuntime(store,{people:()=>staff}).get(access(),task.id).runtime.handoff.taskId,next.id);assert.throws(()=>r.configureHandoff(access(),task.id,{...config,expectedVersion:task.version},'handoff-002'),e=>e.status===409);});
test('失效收件人阻止交接并通知主管，上游完成结果保留',t=>{const {runtime:r,store}=fixture(t);let task=r.create(access(),body('00'),'create-0001');task=r.configureHandoff(access(),task.id,{...body('02'),expectedVersion:task.version},'handoff-001');r.canNotify=()=>false;while(task.runtime.state==='running')task=done(r,task,task.runtime.nodes.find(n=>n.state==='ready'));assert.equal(task.runtime.state,'completed');task=r.get(access(),task.id);assert.equal(task.runtime.handoff.state,'attention');assert.equal(store.read().tasks.length,1);assert.equal(task.notifications.filter(n=>n.kind==='handoff_blocked').length,1);});
test('已准入主播场次不重复准入，人工决定不能委派专员',t=>{const {runtime:r}=fixture(t);const task=r.create(access(),body('04',{anchorMode:'existing'}),'create-0001');assert.equal(task.runtime.nodes[0].id,'W04.S2.E1');assert.equal(task.runtime.nodes.find(n=>n.id==='W04.S2.E2').owner.number,'M');assert.throws(()=>r.create(access(),{...body('06',{stage:'W06.S2'}),bindings:{'W06.S2.E4':'A'}},'create-0002'),e=>e.status===403);assert.throws(()=>r.create(access(),body('06',{stage:'W06.S6',branch:'review',includeDispute:true}),'create-0003'),e=>e.status===403);});
test('不能越过前置、替同事办理、跨中心派单或借旧任务接口越权',t=>{const {runtime:r}=fixture(t);const task=r.create(access(),body(),'create-0001');assert.throws(()=>done(r,task,task.runtime.nodes[1]),e=>e.status===409);assert.throws(()=>done(r,task,task.runtime.nodes[0],'B'),e=>e.status===404||e.status===403);assert.throws(()=>r.create(access(),{...body(),owner:'X'},'create-0002'),e=>e.status===403);assert.equal(legacyVisible(task,access()),false);assert.equal(runVisible(task,access('X')),false);});
test('人事任务仅参与人可见，受派专员可完成本节点',t=>{const {runtime:r}=fixture(t);let task=r.create(access(),body('06',{stage:'W06.S5',branch:'status'}),'create-0001');assert.equal(runVisible(task,access('B')),false);assert.equal(runVisible(task,{...access('X'),department:true}),false);task=done(r,task,task.runtime.nodes[0]);assert.equal(task.status,'completed');});
test('退回保留旧证据与版本，只重开受影响的下游',t=>{const {runtime:r}=fixture(t);let task=r.create(access(),body(),'create-0001');task=done(r,task,task.runtime.nodes[0]);task=done(r,task,task.runtime.nodes[1]);task=r.command(access('A'),task.id,'return',{expectedVersion:task.version,nodeId:task.runtime.nodes[2].id,targetNodeId:task.runtime.nodes[1].id,note:'来源说明需补充'},'return-001');assert.equal(task.runtime.nodes[0].state,'completed');assert.equal(task.runtime.nodes[1].state,'ready');assert.equal(task.runtime.nodes[1].history[0].evidence[0].reference,'work-42');assert.equal(task.runtime.nodes[1].attempt,2);assert.equal(task.runtime.nodes[2].state,'pending');});
test('超时提醒与升级只发一次，暂停不计超时且恢复重新送达',t=>{const {runtime:r,advance,clock}=fixture(t);let task=r.create(access(),body(),'create-0001');task=r.command(access(),task.id,'pause',{expectedVersion:task.version,note:'等待已确认资料'},'pause-001');advance(2*3600000);r.tick();assert.equal(r.get(access(),task.id).notifications.filter(n=>n.kind==='overdue').length,0);task=r.command(access(),task.id,'resume',{expectedVersion:task.version,note:'资料已齐'},'resume-01');assert.equal(Date.parse(task.runtime.nodes[0].dueAt),clock()+3600000);assert.equal(task.notifications.filter(n=>n.kind==='ready').length,2);advance(3600001);r.tick();r.tick();advance(24*3600000);r.tick();r.tick();const notices=r.get(access(),task.id).notifications;assert.equal(notices.filter(n=>n.kind==='overdue').length,1);assert.equal(notices.filter(n=>n.kind==='escalated').length,1);});
function notifier(f,fetchImpl,map={A:'ou_a',M:'ou_m'}){return new FlowFeishu(f.store,{clock:f.clock,people:()=>staff,fetchImpl,env:{FLOW_NOTIFICATIONS_ENABLED:'true',FEISHU_APP_ID:'test',FEISHU_APP_SECRET:'test',FEISHU_RECIPIENT_MAP_JSON:JSON.stringify(map)}});}
const response=d=>({ok:true,status:200,json:async()=>d});
test('暂停飞书发送保留有效人员绑定与任务队列，不发送外部消息',async t=>{const f=fixture(t);let calls=0;const n=notifier(f,async()=>{calls++;throw Error('dispatch paused');});n.enabled=false;const r=new FlowRuntime(f.store,{people:()=>staff,clock:f.clock,canNotify:number=>n.canQueue(number)});assert.equal(n.canQueue('A'),true);assert.equal(n.canQueue('B'),false);const task=r.create(access(),body(),'paused-dispatch-001');await n.flush();const notice=r.get(access(),task.id).notifications[0];assert.equal(calls,0);assert.equal(notice.state,'ready');assert.equal(notice.messageId,null);assert.throws(()=>r.create(access(),{...body(),owner:'B'},'unmapped-paused-001'),e=>e.status===409||e.status===400);n.appId='';assert.equal(n.canQueue('A'),false);});
test('飞书真实成功格式才记送达，幂等编号重试保持一致',async t=>{const f=fixture(t);const task=f.runtime.create(access(),body(),'create-0001'),sent=[];let attempts=0;const n=notifier(f,async(url,init)=>{if(url.includes('/auth/'))return response({code:0,tenant_access_token:'test',expire:7200});sent.push(JSON.parse(init.body));if(!attempts++)throw Error('response lost');return response({code:0,data:{message_id:'om_receipt'}});});await n.flush();assert.equal(f.runtime.get(access(),task.id).notifications[0].state,'ready');f.advance(15000);await n.flush();assert.equal(sent[0].uuid,sent[1].uuid);assert.equal(f.runtime.get(access(),task.id).notifications[0].messageId,'om_receipt');await n.flush();assert.equal(sent.length,2);});
test('缺少飞书映射不会误投同名或伪装送达',async t=>{const f=fixture(t);const task=f.runtime.create(access(),body(),'create-0001');const n=notifier(f,()=>{throw Error('must not send');},{});await n.flush();const row=f.runtime.get(access(),task.id).notifications[0];assert.equal(row.state,'attention');assert.equal(row.messageId,null);});
test('飞书令牌失效只刷新一次且消息编号不变',async t=>{const f=fixture(t);const task=f.runtime.create(access(),body(),'create-0001'),sent=[];let tokens=0;const n=notifier(f,async(url,init)=>{if(url.includes('/auth/')){tokens++;return response({code:0,tenant_access_token:'token'+tokens});}sent.push(JSON.parse(init.body));return sent.length===1?response({code:99991663}):response({code:0,data:{message_id:'om_refreshed'}});});await n.flush();assert.equal(tokens,2);assert.equal(sent[0].uuid,sent[1].uuid);assert.equal(f.runtime.get(access(),task.id).notifications[0].messageId,'om_refreshed');});
test('进程中断超过飞书幂等窗口时停止发送并保留不确定状态',async t=>{const f=fixture(t);const task=f.runtime.create(access(),body(),'create-0001');f.store.transaction(s=>{Object.assign(s.flowNotifications[0],{state:'sending',firstAttemptAt:f.runtime.iso(),leaseUntil:f.clock()+45000});return true;});f.advance(3600001);const n=notifier(f,()=>{throw Error('must not send');});await n.flush();const row=f.store.read().flowNotifications[0];assert.equal(row.state,'attention');assert.equal(row.unknown,true);assert.throws(()=>n.retry(access(),row.id),e=>e.status===409);});
test('负责人失效立即通知主管一次，调整后清除异常并保留旧记录',t=>{const f=fixture(t);let task=f.runtime.create(access(),body(),'create-0001');f.runtime.people=()=>staff.filter(p=>p.number!=='A');f.runtime.tick();f.runtime.tick();task=f.runtime.get(access(),task.id);assert.equal(task.notifications.filter(n=>n.kind==='assignment_attention').length,1);assert.ok(task.runtime.assignmentIssue.message.includes('制作'));f.runtime.people=()=>staff;f.runtime.tick();task=f.runtime.get(access(),task.id);assert.equal(task.runtime.assignmentIssue,undefined);assert.ok(task.flowEvents.some(e=>e.action==='assignment_attention'));});
test('已完成或换主责的旧通知停止发送，人事通知隐藏敏感详情',async t=>{const f=fixture(t);let task=f.runtime.create(access(),body('06',{stage:'W06.S5',branch:'status'}),'create-0001');const sent=[],n=notifier(f,async(url,init)=>url.includes('/auth/')?response({code:0,tenant_access_token:'test'}):(sent.push(JSON.parse(init.body)),response({code:0,data:{message_id:'om_x'}})));await n.flush();assert.ok(!sent[0].content.includes('真实事项'));task=done(f.runtime,task,task.runtime.nodes[0]);await n.flush();assert.equal(sent.length,2);});

for(const origin of ['timeout','server-error','interrupted'])test('通知不确定状态跨后续失败保留：'+origin,async t=>{
 const f=fixture(t);f.runtime.create(access(),body(),'sticky-unknown-001');let sends=0;
 if(origin==='interrupted'){f.store.transaction(s=>{Object.assign(s.flowNotifications[0],{state:'sending',firstAttemptAt:new Date(f.clock()).toISOString(),leaseUntil:f.clock()-1});return true;});}
 const n=notifier(f,async url=>{
  if(url.includes('/auth/'))return response({code:0,tenant_access_token:'test'});
  sends++;if(sends===1&&origin==='timeout')throw Error('lost receipt');
  const status=sends===1&&origin==='server-error'?503:429;
  return {ok:false,status,json:async()=>({code:status})};
 });
 for(let i=0;i<5;i++){await n.flush();assert.equal(f.store.read().flowNotifications[0].unknown,true);f.advance(130000);}
 const row=f.store.read().flowNotifications[0];assert.equal(row.state,'attention');assert.equal(sends,5);
 f.advance(3600000);assert.throws(()=>n.retry(access(),row.id),e=>e.status===409);await n.flush();assert.equal(sends,5);
});
test('明确成功回执才解除先前发送不确定状态',async t=>{
 const f=fixture(t);f.runtime.create(access(),body(),'receipt-clears-001');let sends=0;
 const n=notifier(f,async url=>{if(url.includes('/auth/'))return response({code:0,tenant_access_token:'test'});if(++sends===1)throw Error('lost receipt');return response({code:0,data:{message_id:'om_verified'}});});
 await n.flush();assert.equal(f.store.read().flowNotifications[0].unknown,true);f.advance(15000);await n.flush();
 const row=f.store.read().flowNotifications[0];assert.equal(row.state,'sent');assert.equal(row.unknown,false);assert.equal(row.messageId,'om_verified');
});

test('概览超时统计只包含运行任务，暂停与恢复保留原记录',t=>{
 const f=fixture(t);let paused=f.runtime.create(access(),body(),'paused-metric-001');
 paused=f.runtime.command(access(),paused.id,'pause',{expectedVersion:paused.version,note:'等待来源'},'pause-metric-001');
 f.runtime.create(access(),body(),'running-metric-001');f.advance(3600001);
 const before=JSON.stringify(f.store.read()),metrics=f.runtime.overview(access()).metrics;
 assert.equal(metrics.runs,2);assert.equal(metrics.active,1);assert.equal(metrics.overdue,1);
 assert.equal(JSON.stringify(f.store.read()),before);
 paused=f.runtime.command(access(),paused.id,'resume',{expectedVersion:paused.version,note:'来源已备齐'},'resume-metric-001');
 assert.equal(f.runtime.overview(access()).metrics.active,2);assert.equal(f.runtime.overview(access()).metrics.overdue,1);
});
