// Isolated actors, task stores and source snapshots. These checks do not
// substitute for independent colleagues' real authenticated acceptance.
import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtempSync,rmSync,readFileSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join,resolve,sep} from 'node:path';
import {WorkflowStore} from './workflow-store.mjs';
import {FlowRuntime,runVisible} from './flow-runtime.mjs';
import {FlowBlueprints} from './flow-blueprints.mjs';
import {FlowSources} from './flow-sources.mjs';
import {FlowDelivery} from './flow-delivery.mjs';
import {createFlowHandler} from './flow-http.mjs';
import {modules} from './flow-catalog.mjs';

const people=[
 {number:'M',name:'本中心主管',role:'manager',center:'A'},
 {number:'A',name:'本任务制作',role:'specialist',center:'A'},
 {number:'B',name:'本任务审核',role:'specialist',center:'A'},
 {number:'C',name:'另一任务制作',role:'specialist',center:'A'},
 {number:'X',name:'其他中心主管',role:'manager',center:'B'},
 {number:'D',name:'部门总监',role:'director',center:'管理'},
 {number:'P',name:'技术维护',role:'maintainer',center:'A'},
].map(p=>({...p,active:true,modules:Object.values(modules).filter(Boolean)}));
const access=(number='M')=>{const user=people.find(p=>p.number===number);return {enabled:['manager','director','specialist'].includes(user.role),canManage:['manager','director'].includes(user.role),department:user.role==='director',user,modules:user.modules};};
const taskBody=(extra={})=>({workflow:'02',mode:'simple',title:'本任务制作交付',owner:'A',manager:'M',reviewer:'B',acceptance:'交付本任务文件并审核',product:'晶润紧致眼膜',sourceUrl:'',...extra});
const evidence=[{url:'https://example.invalid/fixture',reference:'isolated-evidence',version:'1'}];
function fixture(t){const root=resolve(tmpdir()),dir=mkdtempSync(join(root,'flow-permission-'));t.after(()=>{assert.ok(resolve(dir).startsWith(root+sep));rmSync(dir,{recursive:true,force:true});});
 const store=new WorkflowStore(join(dir,'tasks.json')),runtime=new FlowRuntime(store,{people:()=>people}),blueprints=new FlowBlueprints(runtime),sources=new FlowSources();runtime.blueprints=blueprints;
 sources.data={cloud:{state:'connected',checkedAt:new Date().toISOString(),people,requests:[],returns:[],reviews:[],deliveries:[]},remix:{state:'connected',checkedAt:new Date().toISOString(),renders:[],jobs:[],inventory:[{product:'GLOBAL_INVENTORY',clips:9000}]}};
 const spies={active:0,globalNotices:0,viewTask:0};const originalActive=blueprints.active.bind(blueprints),originalTaskView=sources.viewTask.bind(sources);blueprints.active=(...args)=>{spies.active++;return originalActive(...args);};sources.viewTask=(...args)=>{spies.viewTask++;return originalTaskView(...args);};
 const delivery=new FlowDelivery({runtime,root:join(dir,'deliveries'),readCloud:async()=>{throw Error('No external requests allowed in this suite');}});
 const http=async(number,method,path,body={})=>{let result;const handler=createFlowHandler({runtime,blueprints,sources,delivery,notifier:{status:()=>{spies.globalNotices++;return {total:9999,mapped:8888};},recipient:()=>null},automation:{view:()=>[]},currentSession:async()=>({status:200,payload:{}}),accessFor:()=>access(number),previewFor:()=>({active:false}),readJson:async()=>body,sendJson:(_,status,body)=>result={status,body}});await handler({method,headers:{host:'example.invalid',origin:'https://example.invalid','x-flow-request':'1','content-type':'application/json','idempotency-key':'isolated-'+method+'-'+path}}, {},new URL('https://example.invalid/api/flows/'+path));return result;};
 return {store,runtime,blueprints,sources,spies,http,delivery};
}
function finish(f,id){let task=f.runtime.get(access(),id);while(task.runtime.state==='running'){const n=task.runtime.nodes.find(n=>n.state==='ready');task=f.runtime.command(access(n.owner.number),id,'complete',{expectedVersion:task.version,nodeId:n.id,note:'隔离核验交付',evidence},'finish-'+id+'-'+n.id,{verifiedEvidence:n.evidenceKind==='human_attested'?null:[{...evidence[0],source:'isolated_test_fixture'}]});}return f.runtime.get(access(),id);}
function linked(f,{childOwner='C',childReviewer='M'}={}){const d=f.blueprints.default(access());d.moduleOrder=['02','01'];f.blueprints.save(access(),{config:d,expectedVersion:0},'publish-links',{publish:true});let parent=f.runtime.create(access(),taskBody({title:'上游隔离私有标题'}),'create-parent');parent=f.runtime.configureHandoff(access(),parent.id,{...taskBody({workflow:'01',owner:childOwner,reviewer:childReviewer,title:'下游隔离私有标题',acceptance:'下游独立交付标准',options:{production:'ai'}}),expectedVersion:parent.version},'configure-child');parent=finish(f,parent.id);return {parent,child:f.runtime.get(access(),parent.runtime.handoff.taskId)};}

test('普通同事直接访问全景、编排及配置旁路全部 403，不能靠隐藏按钮保护',async t=>{const f=fixture(t),before=JSON.stringify(f.store.read());for(const [method,path]of [['GET','catalog'],['GET','sources'],['GET','data-catalog'],['GET','preview'],['POST','preview'],['GET','blueprints'],['GET','blueprints/revision/1'],['GET','blueprints/nodes'],['POST','blueprints/nodes'],['POST','blueprints/preview'],['POST','blueprints/save'],['POST','blueprints/publish'],['GET','automation/watches'],['POST','automation/watches']])assert.equal((await f.http('A',method,path)).status,403,method+' '+path);assert.equal(f.spies.active,0);assert.equal(JSON.stringify(f.store.read()),before);assert.throws(()=>f.blueprints.view(access('A')),e=>e.status===403);});

test('主管与总监可读各自授权配置，专员无任务时目录和关系为空',async t=>{const f=fixture(t);for(const actor of ['M','D']){assert.equal((await f.http(actor,'GET','catalog')).status,200);assert.equal((await f.http(actor,'GET','blueprints')).status,200);}const o=(await f.http('A','GET','overview')).body;assert.deepEqual(o.tasks,[]);assert.deepEqual(o.taskCatalog,{flows:[],stages:[]});assert.equal(o.access.canManage,false);});

test('个人概览只含参与任务标签和真实 dependencies，不读取全局蓝图与通知状态',async t=>{const f=fixture(t),own=f.runtime.create(access(),taskBody(),'create-own');f.runtime.create(access(),taskBody({workflow:'01',owner:'C',reviewer:'M',title:'不得出现的其他流程',options:{production:'ai'}}),'create-other');f.spies.active=0;const before=JSON.stringify(f.store.read()),o=(await f.http('A','GET','overview')).body;assert.equal(f.spies.active,0);assert.equal(f.spies.globalNotices,0);assert.deepEqual(o.tasks.map(x=>x.id),[own.id]);assert.deepEqual(o.tasks[0].nodes.map(n=>n.dependencies),own.runtime.nodes.map(n=>n.dependencies));assert.deepEqual(o.taskCatalog.flows.map(x=>x.id),['02']);assert.deepEqual(Object.keys(o.taskCatalog.flows[0]).sort(),['id','module','name','short']);for(const key of ['flows','blueprint','executionRoutes','notifications'])assert.equal(Object.hasOwn(o,key),false,key);assert.ok(!JSON.stringify(o).includes('不得出现的其他流程'));assert.equal(JSON.stringify(f.store.read()),before);});

test('流程门禁同时核验界面开关与有效业务角色，不接受 access 内伪造管理权限',async()=>{const {configurationAccess}=await import('./flow-configuration-access.mjs');const source=readFileSync(new URL('./server.mjs',import.meta.url),'utf8'),match=source.match(/const flowAccessFor = payload => \{([\s\S]*?)\n\};/);assert.ok(match);const evaluate=new Function('taskCenterUser','inactiveWorkflowMembers','configurationAccess','readConfigurationGrants','join','dataRoot','return payload => {'+match[1]+'}')(p=>p.user,new Set(['INACTIVE']),configurationAccess,()=>[],join,'isolated-unread-test-root');for(const role of ['specialist','maintainer','external']){const a=evaluate({user:{number:'ADMIN',role},workspace:{is_brand_department:true,dashboard_scope:'department'},access:{permissions:{manage_permissions:true},allowed_modules:[...Object.values(modules),'workflow-engine']}});assert.equal(a.canManage,false,role);if(role==='maintainer')assert.equal(a.enabled,false);}for(const role of ['manager','director']){assert.equal(evaluate({user:{number:'M',role},workspace:{is_brand_department:true},access:{allowed_modules:['workflow-engine']}}).canManage,true);assert.equal(evaluate({user:{number:'M',role},workspace:{is_brand_department:true},access:{allowed_modules:[]}}).enabled,false);}assert.equal(evaluate({user:{number:'INACTIVE',role:'director'},workspace:{is_brand_department:true},access:{allowed_modules:['workflow-engine']}}).enabled,false);});

test('个人任务详情不携带整份蓝图或未来交接配置，存储版本不被投影修改',t=>{const f=fixture(t),d=f.blueprints.default(access());d.name='GLOBAL_BLUEPRINT_SECRET';d.moduleOrder=['02','01'];f.blueprints.save(access(),{config:d,expectedVersion:0},'publish-private',{publish:true});let task=f.runtime.create(access(),taskBody(),'create-private');task=f.runtime.configureHandoff(access(),task.id,{...taskBody({workflow:'01',owner:'C',reviewer:'M',title:'FUTURE_TASK_SECRET',options:{production:'ai'}}),expectedVersion:task.version},'configure-private');const before=JSON.stringify(f.store.read()),personal=f.runtime.get(access('A'),task.id);for(const key of ['blueprint','handoff','blueprintTriggers','routingIssues','options'])assert.equal(Object.hasOwn(personal.runtime,key),false,key);assert.ok(!JSON.stringify(personal).includes('GLOBAL_BLUEPRINT_SECRET'));assert.ok(!JSON.stringify(personal).includes('FUTURE_TASK_SECRET'));assert.deepEqual(personal.relations,{upstream:[],downstream:[]});assert.equal(f.runtime.get(access(),task.id).runtime.blueprint.name,d.name);assert.equal(JSON.stringify(f.store.read()),before);});

test('真实交接到不参与的任务不泄露其标题或正文，关系不会授予读取和办理权限',async t=>{const f=fixture(t),{parent,child}=linked(f);const p=f.runtime.get(access('A'),parent.id),c=f.runtime.get(access('C'),child.id);assert.deepEqual(p.relations.downstream,[{title:'下游接收',workflow:child.workflow,state:child.runtime.state,owner:{name:child.assignee.name,number:child.assignee.number},canOpen:false}]);assert.deepEqual(c.relations.upstream,[{title:'上游交接',workflow:parent.workflow,state:parent.runtime.state,owner:{name:parent.assignee.name,number:parent.assignee.number},canOpen:false}]);assert.ok(!JSON.stringify(p).includes(child.id));assert.ok(!JSON.stringify(p).includes(child.title));assert.ok(!JSON.stringify(c).includes(parent.id));assert.ok(!JSON.stringify(c).includes(parent.title));assert.equal(c.sourceUrl,'');assert.equal(runVisible(child,access('A')),false);assert.equal((await f.http('A','GET','runs/'+child.id)).status,404);assert.equal((await f.http('A','POST','runs/'+child.id+'/complete',{expectedVersion:child.version,nodeId:child.runtime.nodes[0].id,note:'不得越权',evidence})).status,404);assert.equal((await f.http('A','GET','runs/'+child.id+'/delivery-options?nodeId='+child.runtime.nodes[0].id)).status,404);assert.throws(()=>f.delivery.content(access('A'),child.id,'attachment_'+'a'.repeat(32)),e=>e.status===404);});

test('本来可见的上下游仅返回直接关系摘要，详情与概览一致',t=>{const f=fixture(t),{parent,child}=linked(f,{childOwner:'A',childReviewer:'B'});const p=f.runtime.get(access('A'),parent.id),c=f.runtime.get(access('A'),child.id),o=f.runtime.overview(access('A'));assert.deepEqual(p.relations.downstream,[{taskId:child.id,title:child.title,workflow:child.workflow,state:child.runtime.state,owner:{name:child.assignee.name,number:child.assignee.number},canOpen:true}]);assert.equal(c.relations.upstream[0].taskId,parent.id);assert.deepEqual(o.tasks.find(x=>x.id===parent.id).relations,p.relations);assert.ok(!Object.hasOwn(p.relations.downstream[0],'acceptance'));assert.ok(!Object.hasOwn(p.relations.downstream[0],'runtime'));});

test('孤立 parentTaskId、伪造单向 handoff 和部门人事关联不进入关系摘要',t=>{const f=fixture(t),a=f.runtime.create(access(),taskBody(),'create-edge-a'),b=f.runtime.create(access(),taskBody({owner:'A',workflow:'01',options:{production:'ai'}}),'create-edge-b');f.store.transaction(s=>{s.tasks.find(x=>x.id===b.id).runtime.parentTaskId=a.id;return true;});assert.deepEqual(f.runtime.get(access('A'),b.id).relations.upstream,[]);f.store.transaction(s=>{const parent=s.tasks.find(x=>x.id===a.id),child=s.tasks.find(x=>x.id===b.id);delete child.runtime.parentTaskId;parent.runtime.handoff={state:'dispatched',taskId:b.id};return true;});assert.deepEqual(f.runtime.get(access('A'),a.id).relations.downstream,[]);const hr=f.runtime.create(access(),{workflow:'06',options:{stage:'W06.S5',branch:'status'},title:'受限人事资料',owner:'C',acceptance:'独立授权'},'create-edge-hr');f.store.transaction(s=>{const parent=s.tasks.find(x=>x.id===a.id),child=s.tasks.find(x=>x.id===hr.id);parent.runtime.handoff={state:'dispatched',taskId:hr.id};child.runtime.parentTaskId=a.id;return true;});assert.deepEqual(f.runtime.get(access(),a.id).relations.downstream,[]);assert.equal(runVisible(hr,access('D')),false);});

test('真实根条件分支也返回可见的直接关系，不开放孙任务的传递访问',t=>{const f=fixture(t),d=f.blueprints.default(access());d.moduleOrder=['02','01'];d.branches=[{after:'02',next:'01',when:'source_shortage'}];f.blueprints.save(access(),{config:d,expectedVersion:0},'publish-branch',{publish:true});const parent=f.runtime.create(access(),taskBody(),'create-branch');f.store.transaction(s=>{const p=s.tasks.find(x=>x.id===parent.id);f.blueprints.triggerSource(s,p,'source_shortage');return true;});const child=f.store.read().tasks.find(t=>t.runtime.parentTaskId===parent.id);assert.ok(child);assert.equal(f.runtime.get(access('A'),parent.id).relations.downstream[0].taskId,child.id);let next=f.runtime.configureHandoff(access(),child.id,{...taskBody({owner:'C',reviewer:'M',title:'仅孙任务可见资料'}),expectedVersion:child.version},'grandchild-config');next=finish(f,next.id);assert.equal(f.runtime.get(access('A'),parent.id).relations.downstream.length,1);assert.ok(!JSON.stringify(f.runtime.get(access('A'),parent.id)).includes(next.runtime.handoff.taskId));});

test('中心管理范围和模块授权保持原界限，关系不会绕过模块撤权',t=>{const f=fixture(t),{parent,child}=linked(f,{childOwner:'A'});assert.equal(runVisible(parent,access('X')),false);assert.equal(f.runtime.overview(access('X')).tasks.length,0);const limited={...access('A'),modules:['material-workbench']};assert.equal(f.runtime.get(limited,parent.id).relations.downstream[0].canOpen,false);assert.equal(f.runtime.get(limited,parent.id).relations.downstream[0].taskId,undefined);assert.throws(()=>f.runtime.get(limited,child.id),e=>e.status===404);assert.ok(f.runtime.overview(access('D')).tasks.some(x=>x.id===parent.id));});

test('总监跨中心交接不让上游主管取得另一中心下游任务资料',t=>{const f=fixture(t);let parent=f.runtime.create(access('D'),taskBody({workflow:'00'}),'director-parent');parent=f.runtime.configureHandoff(access('D'),parent.id,{...taskBody({owner:'X',manager:'X',reviewer:'X',title:'异中心下游标题'}),expectedVersion:parent.version},'director-cross-center');finish(f,parent.id);const full=f.runtime.get(access('D'),parent.id),child=f.runtime.get(access('D'),full.runtime.handoff.taskId),limited=f.runtime.get(access('M'),parent.id);assert.equal(limited.relations.downstream[0].canOpen,false);assert.equal(limited.relations.downstream[0].taskId,undefined);assert.deepEqual(limited.runtime.handoff,{state:'dispatched'});assert.ok(!JSON.stringify(limited).includes(child.id));assert.ok(!JSON.stringify(limited).includes(child.title));assert.equal(limited.relations.downstream[0].owner.name,child.assignee.name);assert.throws(()=>f.runtime.get(access('M'),child.id),e=>e.status===404);assert.equal(full.relations.downstream[0].taskId,child.id);});

test('个人仍可完成自己的交付和审核，其他参与人不能代办当前节点',async t=>{const f=fixture(t);let task=f.runtime.create(access(),taskBody(),'create-actions');let n=task.runtime.nodes[0];assert.equal((await f.http('B','POST','runs/'+task.id+'/complete',{expectedVersion:task.version,nodeId:n.id,note:'不得代办',evidence})).status,403);let response=await f.http('A','POST','runs/'+task.id+'/complete',{expectedVersion:task.version,nodeId:n.id,note:'本人交付',evidence});assert.equal(response.status,200);task=response.body;n=task.runtime.nodes.find(n=>n.state==='ready');response=await f.http('B','POST','runs/'+task.id+'/complete',{expectedVersion:task.version,nodeId:n.id,note:'本人审核确认',evidence});assert.equal(response.status,200);assert.equal(response.body.runtime.state,'completed');assert.equal(response.body.runtime.blueprint,undefined);});

function standardAtRender(f){let task=f.runtime.create(access(),taskBody({mode:'standard',bindings:{'W02.S1.E1':'B'}}),'create-standard-render');while(!task.runtime.nodes.some(n=>n.id==='W02.S4.E1'&&n.state==='ready')){const n=task.runtime.nodes.find(n=>n.state==='ready');task=f.runtime.command(access(n.owner.number),task.id,'complete',{expectedVersion:task.version,nodeId:n.id,note:'隔离完成前置',evidence},'prepare-'+n.id);}return task;}
function seedSources(f){const render=(id,owner,product,variants=[{id:'v1',sha256:'hash1'},{id:'v2',sha256:'hash2'}])=>({id,owner,product,name:id,variants:variants.map(v=>({...v,filePresent:true,duration:20,review:'pending'}))});f.sources.data.remix.renders=[render('mine','A','晶润紧致眼膜'),render('other-person','C','晶润紧致眼膜'),render('other-product','A','深海次抛')];}

test('任务成片选择仅本节点主责可读，并按本人原权限及本任务产品筛选',async t=>{const f=fixture(t),task=standardAtRender(f);seedSources(f);const path='runs/'+task.id+'/sources?nodeId=W02.S4.E1',r=await f.http('A','GET',path);assert.equal(r.status,200);assert.deepEqual(r.body.renders.map(x=>x.id),['mine']);assert.deepEqual(Object.keys(r.body).sort(),['checkedAt','renders','sources']);assert.ok(!JSON.stringify(r.body).includes('GLOBAL_INVENTORY'));assert.equal((await f.http('B','GET',path)).status,403);assert.equal((await f.http('C','GET',path)).status,404);assert.equal((await f.http('A','GET','runs/'+task.id+'/sources?nodeId=W02.S5.E1')).status,409);assert.equal((await f.http('A','GET','runs/'+task.id+'/sources?nodeId=unknown')).status,404);});

test('成片候选尊重已锁定的版本，源失败不被改写为已连通',async t=>{const f=fixture(t),task=standardAtRender(f);seedSources(f);f.store.transaction(s=>{s.tasks.find(x=>x.id===task.id).runtime.sourceContext={renderId:'mine',variantId:'v2',sha256:'hash2'};return true;});let r=await f.http('A','GET','runs/'+task.id+'/sources?nodeId=W02.S4.E1');assert.deepEqual(r.body.renders.map(x=>[x.id,x.variants.map(v=>v.id)]),[['mine',['v2']]]);f.sources.data.remix.renders[0].variants[1].sha256='changed';r=await f.http('A','GET','runs/'+task.id+'/sources?nodeId=W02.S4.E1');assert.deepEqual(r.body.renders,[]);f.sources.data.cloud.state='unavailable';r=await f.http('A','GET','runs/'+task.id+'/sources?nodeId=W02.S4.E1');assert.equal(r.body.sources.find(s=>s.id==='cloud').state,'unavailable');assert.deepEqual(r.body.renders,[]);});

test('任务成片接口不服务普通附件节点、暂停或自动批次，拒绝前不读取根记录',async t=>{const f=fixture(t),task=f.runtime.create(access(),taskBody(),'create-not-render');assert.equal((await f.http('A','GET','runs/'+task.id+'/sources?nodeId='+task.runtime.nodes[0].id)).status,403);assert.equal(f.spies.viewTask,0);const standard=standardAtRender(f);f.runtime.command(access(),standard.id,'pause',{expectedVersion:standard.version,note:'隔离暂停'},'pause-sources');assert.equal((await f.http('A','GET','runs/'+standard.id+'/sources?nodeId=W02.S4.E1')).status,409);assert.equal(f.spies.viewTask,0);});
