import test from 'node:test';import assert from 'node:assert/strict';import {mkdtempSync,rmSync} from 'node:fs';import {tmpdir} from 'node:os';import {join} from 'node:path';
import {WorkflowStore} from './workflow-store.mjs';import {FlowRuntime} from './flow-runtime.mjs';import {FlowBlueprints} from './flow-blueprints.mjs';import {graphFor,modules} from './flow-catalog.mjs';
const staff=[{number:'M',name:'主管',center:'A',role:'manager',active:true,modules:Object.values(modules)},{number:'A',name:'制作',center:'A',role:'specialist',active:true,modules:Object.values(modules)}];const a={enabled:true,canManage:true,department:false,user:staff[0],modules:Object.values(modules)};
function fixture(t){const dir=mkdtempSync(join(tmpdir(),'blueprint-test-'));t.after(()=>rmSync(dir,{recursive:true,force:true}));const store=new WorkflowStore(join(dir,'tasks.json')),r=new FlowRuntime(store,{people:()=>staff}),b=new FlowBlueprints(r);r.blueprints=b;return {store,r,b};}
function config(b,order){const d=b.default(a);d.moduleOrder=order;d.defaultRoute=true;return d;}
function create(r,flow,key){return r.create(a,{workflow:flow,title:'隔离编排验收',sourceUrl:'https://example.com/brief',acceptance:'验证真实执行顺序和回执保留',owner:'A',manager:'M'},key);}
test('模块可绑定升级负责人，决定节点不能通过间接绑定落到专员',t=>{const {r,b}=fixture(t),d=config(b,['00']);d.modules['00'].owner='task_manager';b.save(a,{config:d,expectedVersion:0},'publish-manager',{publish:true});const task=create(r,'00','create-manager');assert.equal(task.assignee.number,'M');assert.ok(task.runtime.nodes.every(n=>n.owner.number==='M'));d.modules['00'].owner='A';d.modules['00'].bindings={'W00.S1.E2':'task_owner'};assert.throws(()=>b.validate(a,d),e=>e.status===403);});
function finish(r,t){while(t.runtime.state==='running'){const n=t.runtime.nodes.find(n=>n.state==='ready'),evidence=[{url:'https://example.com/output',reference:n.id,version:'fixture'}];t=r.command(a,t.id,'complete',{expectedVersion:t.version,nodeId:n.id,note:'隔离测试凭证',evidence},'complete-'+n.id,{verifiedEvidence:n.evidenceKind!=='human_attested'?[{...evidence[0],source:'isolated_test_fixture'}]:null});}return t;}
test('拖动模块后改变新任务真实路由，已运行任务仍使用旧配置',t=>{const {r,b}=fixture(t);b.save(a,{config:config(b,['01','02','04']),expectedVersion:0},'publish-001',{publish:true});const old=create(r,'01','create-001');b.save(a,{config:config(b,['02','01','04']),expectedVersion:1},'publish-002',{publish:true});const newer=create(r,'02','create-002');assert.equal(old.runtime.blueprint.version,1);assert.equal(newer.runtime.blueprint.version,2);const oldDone=finish(r,old),newDone=finish(r,newer);assert.equal(r.get(a,oldDone.runtime.handoff.taskId).workflow,'02');assert.equal(r.get(a,newDone.runtime.handoff.taskId).workflow,'01');assert.equal(r.get(a,oldDone.runtime.handoff.taskId).runtime.blueprint.version,1);assert.equal(r.get(a,newDone.runtime.handoff.taskId).runtime.blueprint.version,2);});
test('保存草稿不改变运行配置，重复发布不会生成重复版本',t=>{const {b,store}=fixture(t),d=config(b,['01','02']);const request={config:d,expectedVersion:0};b.save(a,request,'publish-001',{publish:true});b.save(a,request,'publish-001',{publish:true});assert.equal(store.read().flowBlueprintRevisions.length,1);d.moduleOrder=['02','01'];b.save(a,{config:d,expectedVersion:1},'save-0001');assert.deepEqual(b.active(a).moduleOrder,['01','02']);assert.equal(b.view(a).draft.version,2);});
test('组织主责配置落实到实际节点，未绑定人员不能发布',t=>{const {r,b}=fixture(t),d=config(b,['02']);d.modules['02'].bindings={'W02.S3.E2':'M'};b.save(a,{config:d,expectedVersion:0},'publish-001',{publish:true});const task=create(r,'02','create-001');assert.equal(task.runtime.nodes.find(n=>n.id==='W02.S3.E2').owner.number,'M');r.canNotify=()=>false;d.modules['02'].owner='A';assert.throws(()=>b.save(a,{config:d,expectedVersion:1},'publish-002',{publish:true}),e=>e.status===409);assert.equal(b.active(a).version,1);});
test('脚本可以提前准备，删除必选节点或把交付放在审核前会被拦截',t=>{const {r,b}=fixture(t),d=config(b,['02']);const nodes=graphFor('02');const order=['W02.S1','W02.S3','W02.S2','W02.S4','W02.S5'].flatMap(stage=>nodes.filter(n=>n.stageId===stage).map(n=>n.id));d.modules['02'].nodeOrder=order;b.save(a,{config:d,expectedVersion:0},'publish-001',{publish:true});assert.deepEqual(create(r,'02','create-001').runtime.nodes.map(n=>n.id),order);d.modules['02'].nodeOrder=order.slice(1);assert.throws(()=>b.validate(a,d));d.modules['02'].nodeOrder=[...order.slice(-2),...order.slice(0,-2)];assert.throws(()=>b.validate(a,d));});
test('产品条件优先于默认顺序，条件与发布版本可追溯',t=>{const {r,b}=fixture(t),d=config(b,['00','01','02']);d.branches=[{after:'00',next:'02',when:'black_mask'}];b.save(a,{config:d,expectedVersion:0},'publish-001',{publish:true});const task=r.create(a,{workflow:'00',product:'黑晶面膜',title:'条件分支隔离验收',sourceUrl:'https://example.com',acceptance:'条件路由',owner:'A'},'create-001');const done=finish(r,task);assert.equal(r.get(a,done.runtime.handoff.taskId).workflow,'02');assert.equal(done.runtime.handoff.blueprintRule,'branch-0');});
test('补源根数据事件只创建一次一创任务，原二创任务保留',t=>{const {r,b,store}=fixture(t),d=config(b,['02','01']);d.branches=[{after:'02',next:'01',when:'source_shortage'}];b.save(a,{config:d,expectedVersion:0},'publish-001',{publish:true});const task=create(r,'02','create-001');store.transaction(s=>{const row=s.tasks.find(x=>x.id===task.id);row.runtime.automation={runId:'run-fixture',issue:'合格来源不足'};b.triggerSource(s,row,'source_shortage');b.triggerSource(s,row,'source_shortage');return true;});assert.equal(store.read().tasks.length,2);assert.equal(r.get(a,task.id).runtime.state,'running');assert.equal(store.read().tasks[1].workflow,'01');assert.ok(r.get(a,task.id).runtime.blueprintTriggers['source:source_shortage'].taskId);});
test('已发布配置不允许通过请求体伪造，且专员不能发布部门流程',t=>{const {r,b}=fixture(t);const task=r.create(a,{workflow:'00',title:'测试伪造配置',sourceUrl:'https://example.com',acceptance:'测试',owner:'A',_blueprint:{defaultRoute:true,moduleOrder:['00','01']}},'create-001');assert.equal(task.runtime.blueprint,null);assert.throws(()=>b.save({...a,canManage:false},{config:config(b,['00']),expectedVersion:0},'publish-001',{publish:true}),e=>e.status===403);});
test('实际任务遵守已发布的制作分支和岗位绑定，表单默认值不会覆盖',t=>{const {r,b}=fixture(t),d=config(b,['01']);d.modules['01'].options={production:'shoot'};const nodes=graphFor('01',{production:'shoot'});d.modules['01'].nodeOrder=nodes.map(n=>n.id);d.modules['01'].bindings={[nodes[0].id]:'M'};b.save(a,{config:d,expectedVersion:0},'publish-001',{publish:true});const task=r.create(a,{workflow:'01',title:'配置生效验收',sourceUrl:'https://example.com',acceptance:'实拍分支',owner:'A',options:{production:'ai'},bindings:{[nodes[0].id]:'A'}},'create-001');assert.equal(task.runtime.options.production,'shoot');assert.equal(task.runtime.nodes[0].owner.number,'M');assert.deepEqual(task.runtime.nodes.map(n=>n.id),nodes.map(n=>n.id));});
