const eventPages=new Map();
function moduleGraphEdges(flows){const ids=new Set(flows.map(f=>f.id));const rows=state.catalog.moduleEdges||(state.catalog.edges||[]).map(([from,to,label])=>({from,to,label,type:'reference',enabled:false}));return rows.filter(e=>ids.has(e.from)&&ids.has(e.to));}
function resolvedNodesFor(flow){const f=state.catalog.flows.find(f=>f.id===flow);return f?.resolvedNodes?.length?f.resolvedNodes:state.catalog.stages.filter(s=>s.flow===flow).flatMap(s=>s.steps.map(n=>({...n,stageId:s.id,dependencies:[]})));}
function board(){
 if(!state.overview?.access.canManage)return '';
 const selected=state.catalog.flows.find(f=>f.id===state.flow);
 const flows=state.catalog.flows.filter(f=>(!selected||f.id===selected.id)&&hasSearch(f.name+' '+f.short+' '+f.goal+' '+state.catalog.stages.filter(s=>s.flow===f.id).map(s=>s.title+' '+s.output+' '+s.steps.map(n=>n.title).join(' ')).join(' ')));
 const heading=`<div class="board-heading"><div class="canvas-breadcrumbs"><button class="button quiet" data-canvas-level="flows">全部流程</button>${selected?`<span>/</span><b>${esc(selected.name)}</b>`:''}</div>${selected?moduleLink(selected.id):'<span class="help">每列是业务流程 · 每张卡片是工作环节 · 点击查看执行节点</span>'}</div>`;
 return heading+(flows.length?swimlaneMarkup(flows):empty('没有匹配的流程内容','清空搜索或选择另一个流程。'));
}
function eventHtml(e,link=false){const title=actionLabels[e.action]||e.action,node=state.task?.runtime.nodes.find(n=>n.id===e.nodeId)?.title||nodeInfo(e.nodeId)?.title||e.nodeId;return `<details class="event-record" data-disclosure="event:${esc(e.id)}"><summary><time>${fmt(e.at)}</time><strong>${esc(title)}</strong><span>${esc(e.actor?.name||'系统')}</span><p>${esc(e.note||node||'状态已保存')}</p></summary><div class="event-record-body">${node?'<p>对应环节：'+esc(node)+'</p>':''}<p>${esc(e.note||'本次没有补充说明。')}</p>${e.evidence?.length?e.evidence.map(v=>`<p><a href="${esc(flowEvidenceUrl(v,e.taskId||state.task?.id))}" target="_blank" rel="noopener">${esc(v.filename||v.reference||'查看交付')}</a> · ${esc(v.version||'')}<br>${esc(v.summary||'')}</p>`).join(''):''}<p class="help">${esc(e.id)}${e.at?' · '+esc(e.at):''}</p>${link?`<button class="button quiet" data-task="${esc(e.taskId)}">打开原任务 →</button>`:''}</div></details>`;}
function eventListHtml(events,key,{link=false,size=8}={}){const pages=Math.max(1,Math.ceil(events.length/size)),page=Math.min(eventPages.get(key)||0,pages-1);eventPages.set(key,page);return events.slice(page*size,page*size+size).map(e=>eventHtml(e,link)).join('')+`<div class="record-pagination"><span class="help">${events.length} 条已加载记录 · 第 ${page+1} / ${pages} 页</span><button class="button quiet" data-event-page="${esc(key)}" data-event-offset="-1" ${page===0?'disabled':''}>上一页</button><button class="button quiet" data-event-page="${esc(key)}" data-event-offset="1" ${page===pages-1?'disabled':''}>下一页</button></div>`;}
function activity(){const events=state.overview.events.filter(e=>hasSearch((actionLabels[e.action]||e.action)+' '+e.note+' '+e.actor?.name));return `<section class="panel"><div class="panel-heading"><div><h2>流转记录</h2><div class="muted">先看时间、办理人与结果，展开可核对具体交付；来源为当前权限内最近记录。</div></div></div>${events.length?eventListHtml(events,'activity',{link:true}):empty('当前没有匹配记录','发起和办理后，记录会自动留在原任务中。')}</section>`;}
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b||b.disabled)return;
 if(b.hasAttribute('data-swimlane-references')){if(!state.overview?.access.canManage)return;state.swimlaneReferences=!state.swimlaneReferences;render();}
 if(b.dataset.canvasFlow){state.flow=b.dataset.canvasFlow;state.canvasLevel='stages';state.canvasStage=null;render();}
 if(b.dataset.canvasStage){state.canvasLevel='nodes';state.canvasStage=b.dataset.canvasStage;render();}
 if(b.dataset.canvasLevel){state.canvasLevel=b.dataset.canvasLevel;if(b.dataset.canvasLevel==='flows')state.flow='all';render();}
 if(b.dataset.canvasDetail){openStage(b.dataset.canvasStageId);state.openNodes.add(b.dataset.canvasDetail);const s=state.catalog.stages.find(s=>s.id===state.stage);$('#drawer .drawer-body').innerHTML=`<div class="drawer-summary"><b>本环节交付</b><p>${esc(s.output)}</p></div>${s.steps.map((n,i)=>nodeHtml(n,i)).join('')}`;}
 if(b.dataset.eventPage){const key=b.dataset.eventPage;eventPages.set(key,Math.max(0,(eventPages.get(key)||0)+Number(b.dataset.eventOffset)));if(key==='activity')render();else renderTask();}
});
