function createStepLabel(step){return ['工作事项','人员与交接','确认并发起'][step-1];}
async function openCreate(flow='00'){
 if(!state.overview.access.canManage)return;
 try{state.people=(await api('people')).items;if(!state.people.length)throw Error('人员尚未同步，请稍后重新打开。');}catch(e){toast(e.message);return;}
 let products=[];try{products=(await api('products')).items||[];}catch{}
 const current=state.overview.access.number;let step=1,graph=null,request=0,previewBusy=false,bodyKey='',bodySignature='';
 showModal('发起工作','填写事项、确认主责，系统按实际交付推进。',`
 <nav class="create-steps" aria-label="发起步骤">${[1,2,3].map(i=>`<button type="button" data-create-step="${i}"><span>${i}</span>${createStepLabel(i)}</button>`).join('')}</nav>
 <section data-create-panel="1"><div class="form-grid"><label class="field"><span>业务流程</span><select name="workflow" id="flow-select">${options(state.catalog.flows.map(f=>[f.id,f.name]),flow)}</select></label><label class="field"><span>产品 / 业务对象（可选）</span><input name="product" aria-label="产品 / 业务对象（可选）" maxlength="100" list="business-products" placeholder="产品、活动、直播间、项目或其他对象"><datalist id="business-products">${products.map(p=>`<option value="${esc(p.value)}">${esc(p.label||p.value)}</option>`).join('')}</datalist></label><label class="field wide"><span>这次要完成什么</span><input name="title" maxlength="120" placeholder="例如：完成新品上市素材审核与交付"></label><label class="field wide"><span>怎样算完成</span><textarea name="acceptance" maxlength="2000" placeholder="写明交付物、数量、使用范围和接收要求。"></textarea></label><label class="field wide"><span>来源链接（可选）</span><input name="sourceUrl" type="url" placeholder="飞书任务书、会议结论或原业务记录"></label></div>
 <fieldset class="mode-choice"><legend>办理方式</legend><label><input type="radio" name="mode" value="simple" checked><span><b>简洁审批与交接</b><small>主责交付 → 审核确认 → 可选下游接收</small></span></label><label><input type="radio" name="mode" value="standard"><span><b>标准业务全流程</b><small>使用已发布的完整环节、分支与业务核验要求</small></span></label></fieldset><p class="help" id="create-mode-note"></p><div id="create-branch-fields"></div></section>
 <section data-create-panel="2" hidden><div class="form-grid"><div class="field"><span>谁负责办理</span>${peoplePicker('owner',{value:current,label:'任务主责'})}</div><div class="field" data-simple-field><span>谁审核交付</span>${peoplePicker('reviewer',{value:current,label:'审核人'})}</div><div class="field" data-simple-field><span>下游接收人（可选）</span>${peoplePicker('receiver',{label:'下游接收人'})}</div><div class="field"><span>流程管理人</span>${peoplePicker('manager',{value:current,label:'流程管理人',managersOnly:true})}</div><label class="field"><span>默认办理时限（小时）</span><input name="slaHours" type="number" min="0.017" max="720" step="0.001" value="24"></label></div><p class="help" id="reviewer-independence">建议由不同同事审核交付，便于发现遗漏。</p><details class="advanced-create" id="create-advanced"><summary>高级岗位设置与来源去重</summary><p class="help">未单独调整的办理节点交给任务主责，决定节点使用流程管理人。已发布的固定配置会保留。</p><label class="field"><span>来源编号（可选）</span><input name="sourceKey" maxlength="200" placeholder="用于同一业务来源防重复发起"></label><div id="create-bindings"></div></details></section>
 <section data-create-panel="3" hidden><div id="create-preview" aria-live="polite"></div></section>`,'下一步');
 const form=$('#edit-form');form.noValidate=true;const next=form.querySelector('button[type=submit]'),footer=form.querySelector('.form-footer');footer.insertAdjacentHTML('afterbegin','<button class="button" type="button" id="create-back" hidden>上一步</button>');initPeoplePickers(form);
 const value=name=>new FormData(form).get(name)||'';
 const mode=()=>value('workflow')==='06'?'standard':value('mode');
 const opts=()=>{const o={};for(const name of ['production','anchorMode','stage','branch'])if(value(name))o[name]=value(name);for(const name of ['includeCoach','includeDispute'])o[name]=value(name)==='on';return o;};
 function payload(){const b={workflow:value('workflow'),mode:mode(),product:value('product').trim(),title:value('title').trim(),sourceUrl:value('sourceUrl').trim(),acceptance:value('acceptance').trim(),owner:value('owner'),reviewer:value('reviewer'),receiver:value('receiver'),manager:value('manager'),slaHours:Number(value('slaHours')),sourceKey:value('sourceKey').trim(),options:opts()};if(b.mode==='standard'){delete b.reviewer;delete b.receiver;b.bindings={};form.querySelectorAll('#create-bindings input[type=hidden][name^="node-"]').forEach(input=>{if(input.value)b.bindings[input.name.slice(5)]=input.value;});}return b;}
 function showError(message){const box=$('#form-error');box.textContent=message;box.hidden=!message;}
 function setStep(n){step=n;form.querySelectorAll('[data-create-panel]').forEach(el=>el.hidden=Number(el.dataset.createPanel)!==step);form.querySelectorAll('[data-create-step]').forEach(el=>{el.classList.toggle('active',Number(el.dataset.createStep)===step);el.setAttribute('aria-current',Number(el.dataset.createStep)===step?'step':'false');});$('#create-back').hidden=step===1;next.textContent=step===3?(state.overview.notifications.enabled?'发起并通知负责人':'发起工作'):'下一步';showError('');if(step===3)void preview(true);form.querySelector('.form-body').scrollTop=0;}
 function validate(until=step){const b=payload();if(until>=1){if(b.title.length<2)throw Error('请填写至少两个字的工作事项。');if(!b.acceptance)throw Error('请写明怎样才算完成。');if(b.sourceUrl){let u;try{u=new URL(b.sourceUrl);}catch{}if(!u||!['https:','http:'].includes(u.protocol))throw Error('来源链接请使用有效的 http 或 https 地址，也可以留空。');}}if(until>=2){for(const name of ['owner','manager',...(b.mode==='simple'?['reviewer']:[]),...(b.receiver?['receiver']:[])]){const p=state.people.find(p=>p.number===b[name]);if(!p)throw Error(({owner:'任务主责',manager:'流程管理人',reviewer:'审核人',receiver:'下游接收人'}[name])+'需要从搜索结果中选择。');if(p.notificationReady===false)throw Error(p.name+' 的飞书尚未绑定，请更换或先完成绑定。');}if(!Number.isFinite(b.slaHours)||b.slaHours<1/60||b.slaHours>720)throw Error('办理时限须在 1 分钟至 30 天内。');}return b;}
 function branchFields(){const f=value('workflow'),standard=mode()==='standard';form.querySelectorAll('[data-simple-field]').forEach(el=>el.hidden=standard);$('#reviewer-independence').hidden=standard;$('#create-advanced').hidden=!standard;const simple=form.querySelector('[name=mode][value=simple]');simple.disabled=f==='06';if(f==='06')form.querySelector('[name=mode][value=standard]').checked=true;$('#create-mode-note').textContent=f==='06'?'部门人事资料使用原独立授权流程，保留必要审核与权限边界。':standard?'完整流程会保留原有业务核验要求；只有需要特殊分工时才展开高级岗位设置。':'简洁流程适用于日常业务事项；审核和接收可沿用主责已提交的交付物。';$('#create-branch-fields').innerHTML=!standard?'':f==='01'?'<label class="field"><span>制作方式</span><select name="production"><option value="ai">AI 制作</option><option value="shoot">实拍制作</option><option value="both">AI 与实拍均必选</option></select></label>':f==='04'?'<label class="field"><span>直播范围</span><select name="anchorMode"><option value="existing">已准入主播的单场直播</option><option value="new">新主播准入后开播</option></select></label><label class="check-field"><input type="checkbox" name="includeCoach">包含直播教练记录</label>':f==='06'?`<label class="field"><span>本次独立事项</span><select name="stage" id="create-hr-stage">${options(state.catalog.stages.filter(s=>s.flow==='06').map(s=>[s.id,s.title]))}</select></label><div id="create-hr-branch"></div>`:'';if(f==='06')hrFields();graph=null;void preview();}
 function hrFields(){const stage=value('stage'),list=stage==='W06.S3'?[['onboarding','已确认入职'],['probation','人工转正评审'],['access','获批岗位权限']]:stage==='W06.S5'?[['status','人员状态登记'],['conversation','沟通与支持']]:stage==='W06.S6'?[['target','周期目标确认'],['review','周期成果评议']]:null;$('#create-hr-branch').innerHTML=list?`<label class="field"><span>办理范围</span><select name="branch">${options(list)}</select></label>${stage==='W06.S6'?'<label class="check-field"><input type="checkbox" name="includeDispute">包含独立绩效复核</label>':''}`:'';}
 async function preview(summary=false){const id=++request;previewBusy=true;if(summary)$('#create-preview').innerHTML='<p class="help">正在核对实际流程、负责人和交付要求…</p>';try{const b=payload(),result=await api('preview',{body:b});if(id!==request||!form.isConnected)return;graph=result;const nodes=result.nodes||[];if(!nodes.length)throw Error('本次流程没有可办理节点，请调整范围。');if(mode()==='standard'&&!summary){const grouped=Map.groupBy?Map.groupBy(nodes,n=>n.stageId||'其他节点'):nodes.reduce((m,n)=>m.set(n.stageId||'其他节点',[...(m.get(n.stageId||'其他节点')||[]),n]),new Map());$('#create-bindings').innerHTML=[...grouped].map(([stage,items])=>`<details><summary>${esc(state.catalog.stages.find(s=>s.id===stage)?.title||stage)} · ${items.length} 个节点</summary>${items.map(n=>{const fixed=result.defaults?.bindings?.[n.id];return `<div class="binding"><span>${esc(n.title)}<small class="help">${fixed?'已发布配置固定人员':n.managerRequired?'默认由流程管理人办理':'默认由任务主责办理'}</small></span>${fixed?`<span>${esc(state.people.find(p=>p.number===fixed)?.name||fixed)}</span>`:peoplePicker('node-'+n.id,{label:n.title,managersOnly:n.managerRequired})}</div>`;}).join('')}</details>`).join('');initPeoplePickers(form);}
  if(summary){const person=number=>state.people.find(p=>p.number===number)?.name||'按流程默认分工';$('#create-preview').innerHTML=`<div class="create-summary"><h3>${esc(b.title)}</h3><p>${esc(b.acceptance)}</p><dl><div><dt>业务对象</dt><dd>${esc(b.product||'不限定')}</dd></div><div><dt>办理方式</dt><dd>${b.mode==='simple'?'简洁审批与交接':'标准业务全流程'}</dd></div><div><dt>流程管理人</dt><dd>${esc(person(b.manager))}</dd></div><div><dt>来源</dt><dd>${b.sourceUrl?`<a href="${esc(b.sourceUrl)}" target="_blank" rel="noopener">查看来源</a>`:'本次直接发起'}</dd></div></dl></div><ol class="create-route">${(b.mode==='simple'?nodes:nodes.filter(n=>!n.dependencies.length||n.managerRequired).slice(0,8)).map(n=>`<li><b>${esc(n.title)}</b><span>${esc(person(n.ownerRule?(result.defaults?.[n.ownerRule]||b[n.ownerRule]):result.defaults?.bindings?.[n.id]||b.bindings?.[n.id]||(n.managerRequired?(result.defaults?.manager||b.manager):(result.defaults?.owner||b.owner))))}</span></li>`).join('')}</ol>${b.mode==='standard'?`<p class="help">本次完整流程共 ${nodes.length} 个执行节点，未单独调整的岗位将使用默认负责人。${result.blueprintVersion?'固定采用已发布 v'+result.blueprintVersion+'。':''}</p>`:''}<p class="help">${state.overview.notifications.enabled?"发起后只通知当前办理人，后续人员在轮到自己时收到通知。":"当前通知发送已暂停；任务和通知队列会保存，恢复发送后可核对送达回执。"}</p>`;}
 }catch(e){if(id!==request)return;graph=null;showError(e.message);if(summary)$('#create-preview').innerHTML='<p class="help">预览尚未通过，本次填写内容已保留。</p>';}finally{if(id===request)previewBusy=false;}}
 form.addEventListener('change',e=>{if(e.target.name==='workflow'||e.target.name==='mode'){branchFields();return;}if(e.target.id==='create-hr-stage')hrFields();if(e.target.closest('#create-branch-fields'))void preview();});
 form.querySelector('.create-steps').addEventListener('click',e=>{const target=e.target.closest('[data-create-step]');if(!target)return;const n=Number(target.dataset.createStep);try{if(n>step)validate(n-1);setStep(n);}catch(error){showError(error.message);}});$('#create-back').onclick=()=>setStep(step-1);
 form.onsubmit=async e=>{e.preventDefault();if(form.dataset.busy==='true')return;try{const b=validate(step);if(step<3){setStep(step+1);return;}if(previewBusy||!graph)throw Error('实际流程仍在核对，请稍候再发起。');const signature=JSON.stringify(b);if(signature!==bodySignature){bodyKey=crypto.randomUUID();bodySignature=signature;}form.dataset.busy='true';form.querySelectorAll('button').forEach(el=>el.disabled=true);const task=await api('runs',{body:b,key:bodyKey});form.dataset.busy='false';$('#modal').close();toast('工作已发起，可在任务中核对当前主责和通知回执。');state.view='tasks';await refresh();await openTask(task.id);}catch(error){showError(error.message+' 本次填写内容已保留。');}finally{form.dataset.busy='false';form.querySelectorAll('button').forEach(el=>el.disabled=false);}};
 branchFields();setStep(1);
}
