const deliveryDrafts=new Map();
let deliveryOpening=null;
function deliveryKey(task,node){return [task.id,node.id,node.attempt].join(':');}
function createDeliveryCloudLoader(readProducts,onChange,isActive){
 let pending=null,current={state:'not_requested',available:false,categories:[]};
 return async function load({retry=false}={}){
  if(pending)return pending;if(current.state==='connected'&&!retry)return current;
  current={state:'loading',available:false,categories:[]};if(isActive())onChange(current);
  pending=(async()=>{try{const result=await readProducts();current={state:result.state,available:result.state==='connected',categories:result.state==='connected'?(result.items||[]):[],detail:result.detail||''};}catch(error){current={state:'unavailable',available:false,categories:[],detail:error.message};}if(isActive())onChange(current);return current;})();
  try{return await pending;}finally{pending=null;}
 };
}
async function uploadTaskAttachment(task,node,file,options,onProgress,prior={}){
 if(file.size>options.maxBytes)throw Error('普通附件最大 '+Math.round(options.maxBytes/1024/1024)+' MB；视频请使用云管家视频上传。');
 const extension=file.name.split('.').at(-1).toLowerCase();if(!options.extensions.includes(extension))throw Error('该文件类型不在允许范围，请使用页面列出的格式。');
 onProgress('正在核验文件',0);const bytes=await file.arrayBuffer(),sha256=[...new Uint8Array(await crypto.subtle.digest('SHA-256',bytes))].map(n=>n.toString(16).padStart(2,'0')).join('');
 const key=prior.requestKey||(prior.requestKey=crypto.randomUUID());prior.sha256=sha256;
 const ticket=await api('runs/'+task.id+'/attachments',{body:{nodeId:node.id,expectedVersion:task.version,filename:file.name,size:file.size,mimeType:file.type||'application/octet-stream',sha256},key});prior.attachmentId=ticket.attachmentId;
 if(ticket.state==='ready')return ticket;
 const url=new URL(flowAttachmentPath(task.id,ticket.attachmentId),location.origin);if(url.origin!==location.origin||!url.pathname.startsWith(API))throw Error('上传入口与当前流程不一致，请刷新核对。');
 onProgress('正在上传文件',20);let response;
 try{response=await fetch(url,{method:'PUT',credentials:'same-origin',redirect:'error',headers:{'Content-Type':'application/octet-stream','X-Flow-Request':'1'},body:bytes,signal:AbortSignal.timeout(120000)});const result=await response.json();if(!response.ok)throw Error(result.detail||'文件上传未完成');if(result.state!=='ready')throw Error('文件仍在核验，请保留此任务稍后读取');onProgress('文件已保存',100);return result;}
 catch(error){const readback=await api('runs/'+task.id+'/delivery-options?nodeId='+encodeURIComponent(node.id)).catch(()=>null);const known=readback?.attachments?.find(a=>a.attachmentId===ticket.attachmentId&&a.state==='ready');if(known){onProgress('已核对原上传成功',100);return known;}throw Error(error.message+'；已保留原上传编号，可核对后续传。');}
}
function deliveryReceiptLabel(item){return item.filename||item.name||item.reference||('资产 '+item.assetId);}
function deliverySelectionRef(item){return item.attachmentId?{attachmentId:item.attachmentId,...(item.reuseFromAttempt!==undefined?{reuseFromAttempt:item.reuseFromAttempt}:{})}:{assetId:item.assetId,version:item.version};}
function previousAttachmentHtml(files,task){return files.length?'<h4>以前轮次已保存的附件</h4><p class="help">先下载核对，再明确选择本轮沿用。提交时重新核验原文件，仍须重新审核；不会重新上传。</p>'+files.map((a,i)=>`<div class="delivery-previous-item"><b>${esc(deliveryReceiptLabel(a))}</b><small>原第 ${esc(a.attempt)} 轮 · ${esc(a.uploadedBy?.name||'原上传人待核对')}</small><div class="actions"><a class="button quiet" href="${esc(flowEvidenceUrl(a,task.id))}" download="${esc(a.filename||'原交付文件')}">下载核对</a><button class="button" type="button" data-previous-attachment="${i}">沿用第 ${esc(a.attempt)} 轮附件</button></div></div>`).join(''):'';}
async function openDeliveryAction(task,node){
 const key=deliveryKey(task,node);if(deliveryOpening?.key===key&&deliveryOpening.form===$('#edit-form')&&$('#modal').open)return;
 const opening={key};deliveryOpening=opening;
 showModal('正在加载交付',node.title+' · '+task.title,'<p class="help" role="status" id="delivery-loading">正在读取原任务的附件与交付要求…</p><button type="button" class="button" id="delivery-open-retry" hidden>重新加载交付</button>','正在加载');
 const loadingForm=$('#edit-form');opening.form=loadingForm;loadingForm.querySelector('[type="submit"]').disabled=true;loadingForm.onsubmit=e=>e.preventDefault();
 const stillOpening=()=>deliveryOpening===opening&&$('#edit-form')===loadingForm&&$('#modal').open;
 let opts;try{opts=await api('runs/'+task.id+'/delivery-options?nodeId='+encodeURIComponent(node.id));}catch(error){if(stillOpening()){loadingForm.querySelector('#delivery-loading').textContent='交付资料暂未读回，原任务与附件保留。';const box=loadingForm.querySelector('#form-error');box.textContent=error.message;box.hidden=false;const retry=loadingForm.querySelector('#delivery-open-retry');retry.hidden=false;retry.onclick=()=>void openDeliveryAction(task,node);}if(deliveryOpening===opening)deliveryOpening=null;return;}
 if(!stillOpening()){if(deliveryOpening===opening)deliveryOpening=null;return;}deliveryOpening=null;
 const draft=deliveryDrafts.get(key)||{selected:new Map(),pending:[],note:'',links:''};deliveryDrafts.set(key,draft);
 const reuse=node.canReuseUpstreamEvidence||opts.canReuseUpstreamEvidence;const upstream=task.runtime.nodes.filter(n=>node.dependencies?.includes(n.id)).flatMap(n=>n.evidence||[]);
 showModal(reuse?'确认'+node.title:'提交交付',node.title+ ' · '+task.title,`<p class="help">${esc(node.done||'提交可供接收人核对的交付物。')}</p>${reuse?`<div class="delivery-inherited"><b>沿用上一步的交付物</b>${upstream.length?upstream.map(e=>`<p>${evidenceLinkHtml(e,task.id)}<small class="help">${esc(e.summary||'')}</small></p>`).join(''):'<p class="help">提交时由服务端核对前置节点的交付凭证。</p>'}<p class="help">无需重复上传。请核对原交付后记录确认结论。</p></div>`:`<div class="delivery-tabs" role="tablist"><button type="button" role="tab" data-delivery-tab="file" aria-selected="true">文件 / 截图</button><button type="button" role="tab" data-delivery-tab="video" aria-selected="false">上传视频</button><button type="button" role="tab" data-delivery-tab="cloud" aria-selected="false">云管家素材</button><button type="button" role="tab" data-delivery-tab="link" aria-selected="false">链接</button></div>
 <section data-delivery-panel="file"><label class="delivery-drop"><b>选择文件，或在此粘贴截图</b><span>文件将保存在原任务，可刷新后继续核对。</span><input id="delivery-files" type="file" multiple accept="${opts.fileUpload.extensions.map(e=>'.'+e).join(',')}"><small>${opts.fileUpload.extensions.join('、')} · 单个不超过 ${Math.round(opts.fileUpload.maxBytes/1024/1024)} MB</small></label><div id="delivery-file-queue"></div><div id="delivery-existing"></div></section>
 <section data-delivery-panel="video" hidden><div id="delivery-cloud-status" role="status" aria-live="polite"><p class="help">进入视频交付时读取云管家分类，文件和截图可先行交付。</p></div><button type="button" class="button" id="delivery-cloud-retry" hidden>重试读取云管家分类</button><fieldset id="delivery-video-controls" disabled style="border:0;padding:0;margin:0;min-width:0"><p class="help">视频上传到你的云管家素材库，按分片保存进度；文件保存后仍沿用原审核要求。</p><div class="form-grid"><label class="field"><span>产品分类</span><input id="delivery-category" value="${esc(task.runtime.product||'')}" list="delivery-categories" placeholder="选择或填写实际产品分类"><datalist id="delivery-categories"></datalist></label><label class="field"><span>素材用途</span><select id="delivery-library"><option value="source" ${task.workflow!=='02'?'selected':''}>源素材</option><option value="remix" ${task.workflow==='02'?'selected':''}>制作成片</option></select></label><label class="field"><span>内容类型</span><input id="delivery-content-type" value="产品展示" placeholder="例如：产品展示、口播、场景演绎"></label></div><label class="delivery-drop"><b>选择要上传的视频</b><span>使用原账号和真实文件校验值，可恢复未完成分片。</span><input id="delivery-video" type="file" accept="video/*"></label><div class="actions"><button type="button" class="button" id="delivery-video-resume" hidden>核对原进度并继续上传</button><button type="button" class="button" id="delivery-video-pause" hidden>暂停上传</button></div><div id="delivery-video-progress" aria-live="polite"></div></fieldset></section>
 <section data-delivery-panel="cloud" hidden><label class="field"><span>查找我有权使用的云管家素材</span><input id="delivery-cloud-search" type="search" placeholder="搜索文件名或产品分类"></label><label class="check-field"><input id="delivery-cloud-all" type="checkbox">同时查找我有权查看的同事素材</label><div id="delivery-cloud-results" aria-live="polite"></div></section>
 <section data-delivery-panel="link" hidden><label class="field"><span>交付链接</span><textarea id="delivery-links" rows="3" placeholder="每行一个 http 或 https 链接">${esc(draft.links)}</textarea></label><p class="help">适用于飞书文档、业务页面等交付，编号和版本由系统记录，不需要手填。</p></section><section class="delivery-selected"><b>本次选用的交付</b><div id="delivery-selected-list"></div></section>`}<label class="field"><span>${reuse?'审核 / 接收结论':'交付说明'}</span><textarea name="note" maxlength="1500" placeholder="写明本次交付内容、核对结果或需要下游关注的事项。">${esc(draft.note)}</textarea></label>`,reuse?'确认并继续流转':'保存交付并流转');
 const form=$('#edit-form');form.noValidate=true;let uploading=false,searchRequest=0,searchTimer,cloudSearchPending=null,keyForSubmit='',signature='';
 const active=()=>form.isConnected&&$('#edit-form')===form&&$('#modal').open;
 const loadCloudCategories=createDeliveryCloudLoader(()=>api('products'),cloud=>{
  opts.cloud={...opts.cloud,...cloud};const box=form.querySelector('#delivery-cloud-status'),retry=form.querySelector('#delivery-cloud-retry'),controls=form.querySelector('#delivery-video-controls'),list=form.querySelector('#delivery-categories');if(!box)return;
  controls.disabled=!cloud.available;retry.hidden=cloud.state==='loading'||cloud.state==='connected';
  box.innerHTML=cloud.state==='loading'?'<p class="help">正在读取云管家真实分类…可以切回文件或链接继续交付。</p>':cloud.available?'<p class="help">云管家分类已读取，上传将继续核验当前账号的权限。</p>':`<p class="form-error">${esc(cloud.detail||(cloud.state==='authorization_required'?'当前账号的云管家授权待确认。':'云管家分类暂未读回。'))}</p><p class="help">原任务、已选文件和交付说明保留，可重试或先用其他方式交付。</p>`;
  list.innerHTML=cloud.categories.map(c=>`<option value="${esc(c.value)}"></option>`).join('');
 },active);
 const showError=message=>{const box=$('#form-error');box.textContent=message;box.hidden=!message;};
 function select(item){const id=item.attachmentId?'file:'+item.attachmentId:'asset:'+item.assetId+':'+item.version;draft.selected.set(id,item);selected();}
 function selected(){const box=$('#delivery-selected-list');if(!box)return;box.innerHTML=draft.selected.size?[...draft.selected].map(([id,item])=>`<div class="delivery-item"><span><b>${esc(deliveryReceiptLabel(item))}</b><small>${item.reuseFromAttempt!==undefined?'沿用第 '+esc(item.reuseFromAttempt)+' 轮附件 · 本次第 '+esc(node.attempt)+' 轮':item.attachmentId?'任务附件已保存':'云素材版本已关联'}${item.size?' · '+(item.size/1024/1024).toFixed(1)+' MB':''}</small></span><button type="button" class="button quiet" data-remove-delivery="${esc(id)}" aria-label="取消选用${esc(deliveryReceiptLabel(item))}">取消选用</button></div>`).join(''):'<p class="help">尚未选择文件或云素材；也可在“链接”中填写交付地址。</p>';}
 function busy(value){uploading=value;form.dataset.busy=String(value);form.querySelectorAll('.form-footer button,[data-close-modal]').forEach(b=>b.disabled=value);}
 function showExisting(){const box=$('#delivery-existing');if(!box)return;const files=(opts.attachments||[]).filter(a=>a.state==='ready'),previous=(opts.previousAttachments||[]).filter(a=>a.state==='ready'&&a.nodeId===node.id&&Number.isSafeInteger(a.attempt)&&a.attempt>=1&&a.attempt<node.attempt);box.innerHTML=(files.length?'<h4>本轮已保存的附件</h4>'+files.map((a,i)=>`<button class="delivery-existing" type="button" data-existing-attachment="${i}">${esc(deliveryReceiptLabel(a))}<span>选用此附件</span></button>`).join(''):'')+previousAttachmentHtml(previous,task);box.onclick=e=>{const current=e.target.closest('[data-existing-attachment]'),old=e.target.closest('[data-previous-attachment]');if(current&&files[Number(current.dataset.existingAttachment)])select(files[Number(current.dataset.existingAttachment)]);if(old&&previous[Number(old.dataset.previousAttachment)]){const item=previous[Number(old.dataset.previousAttachment)];select({...item,reuseFromAttempt:item.attempt});}};}
 function queueHtml(){const box=$('#delivery-file-queue');if(!box)return;box.innerHTML=draft.pending.map((row,i)=>`<div class="upload-row"><b>${esc(row.file.name)}</b><span>${esc(row.label||'等待上传')}</span><progress max="100" value="${row.progress||0}"></progress>${row.error?`<p class="form-error">${esc(row.error)}</p><button class="button" type="button" data-retry-file="${i}">核对原上传并继续</button>`:''}</div>`).join('');}
 async function uploadRow(row){if(uploading)return;busy(true);row.error='';try{const receipt=await uploadTaskAttachment(task,node,row.file,opts.fileUpload,(label,progress)=>{row.label=label;row.progress=progress;queueHtml();},row);select(receipt);opts.attachments=[...(opts.attachments||[]).filter(a=>a.attachmentId!==receipt.attachmentId),receipt];showExisting();}catch(e){row.error=e.message;row.label='上传待处理';queueHtml();}finally{busy(false);}}
 async function addFiles(files){for(const file of files){if(uploading)break;const row={file,label:'等待上传',progress:0};draft.pending.push(row);queueHtml();await uploadRow(row);}}
 function searchCloud(){if(!active())return Promise.resolve();const q=form.querySelector('#delivery-cloud-search')?.value||'',query='runs/'+task.id+'/cloud-assets?nodeId='+encodeURIComponent(node.id)+'&mineOnly='+String(!form.querySelector('#delivery-cloud-all')?.checked)+'&q='+encodeURIComponent(q);if(cloudSearchPending?.query===query)return cloudSearchPending.promise;
  const id=++searchRequest,box=form.querySelector('#delivery-cloud-results'),pending={query};cloudSearchPending=pending;box.innerHTML='<p class="help">正在查询有权使用的素材…</p>';box.onclick=null;
  pending.promise=(async()=>{try{const result=await api(query);if(id!==searchRequest||!active())return;const items=result.items||[];box.innerHTML=items.length?items.map((item,i)=>`<button class="cloud-choice" type="button" data-cloud-choice="${i}"><b>${esc(item.filename||'云素材 '+item.assetId)}</b><span>${esc(item.category||'未分类')} · ${item.size?(item.size/1024/1024).toFixed(1)+' MB':'大小待核验'}</span><small>${esc(item.uploadedBy?.name||item.uploadedBy||'')} · 选用当前版本</small></button>`).join(''):'<p class="help">没有匹配的素材。可换搜索词，或先上传视频。</p>';box.onclick=e=>{const b=e.target.closest('[data-cloud-choice]');if(b)select(items[Number(b.dataset.cloudChoice)]);};}catch(e){if(id===searchRequest&&active())box.innerHTML=`<p class="form-error">${esc(e.message)}</p><button type="button" class="button" data-retry-cloud-search>重新查询原素材</button>`;}finally{if(cloudSearchPending===pending)cloudSearchPending=null;}})();return pending.promise;
 }
 form.addEventListener('input',e=>{if(e.target.name==='note')draft.note=e.target.value;if(e.target.id==='delivery-links')draft.links=e.target.value;if(e.target.id==='delivery-cloud-all')void searchCloud();if(e.target.id==='delivery-cloud-search'){clearTimeout(searchTimer);searchTimer=setTimeout(searchCloud,250);}});
 form.addEventListener('click',e=>{const tab=e.target.closest('[data-delivery-tab]');if(tab){form.querySelectorAll('[data-delivery-tab]').forEach(b=>b.setAttribute('aria-selected',String(b===tab)));form.querySelectorAll('[data-delivery-panel]').forEach(p=>p.hidden=p.dataset.deliveryPanel!==tab.dataset.deliveryTab);if(tab.dataset.deliveryTab==='cloud')void searchCloud();if(tab.dataset.deliveryTab==='video')void loadCloudCategories();}if(e.target.closest('[data-retry-cloud-search]'))void searchCloud();const remove=e.target.closest('[data-remove-delivery]');if(remove){draft.selected.delete(remove.dataset.removeDelivery);selected();}const retry=e.target.closest('[data-retry-file]');if(retry)void uploadRow(draft.pending[Number(retry.dataset.retryFile)]);});
 $('#delivery-files')?.addEventListener('change',e=>{const files=[...e.target.files];e.target.value='';void addFiles(files);});form.addEventListener('paste',e=>{if(reuse||uploading)return;const images=[...(e.clipboardData?.files||[])].filter(f=>f.type.startsWith('image/'));if(images.length){e.preventDefault();void addFiles(images.map(f=>new File([f],f.name&&/\.[a-z]+$/i.test(f.name)?f.name:'截图-'+Date.now()+'.png',{type:f.type})));}});
 if(!reuse){
  $('#delivery-cloud-retry')?.addEventListener('click',()=>void loadCloudCategories({retry:true}));
  let selectedVideo=null,videoAbort=null;
  async function continueVideo(){const file=selectedVideo;if(!file||uploading)return;if(!opts.cloud?.available){showError('云管家分类尚未读回，请重试核验；文件与说明保留。');void loadCloudCategories();return;}const category=$('#delivery-category').value.trim(),contentType=$('#delivery-content-type').value.trim();if(!category||!contentType){showError('请先填写实际产品分类和内容类型。');return;}const box=$('#delivery-video-progress'),resume=$('#delivery-video-resume'),pause=$('#delivery-video-pause');videoAbort=new AbortController();busy(true);showError('');resume.hidden=true;pause.hidden=false;let success=false;
   try{const asset=await performFlowCloudVideoUpload(file,{cloud:opts.cloud,category,libraryType:$('#delivery-library').value,contentType,taskId:task.id,nodeId:node.id,signal:videoAbort.signal,onProgress:(label,progress)=>{box.replaceChildren();const row=document.createElement('div');row.className='upload-row';const name=document.createElement('b');name.textContent=file.name;const status=document.createElement('span');status.textContent=label;const bar=document.createElement('progress');bar.max=100;bar.value=progress;row.append(name,status,bar);box.append(row);}});const canonical=await api('runs/'+task.id+'/cloud-assets/resolve',{body:{nodeId:node.id,assetId:asset.id||asset.assetId}});select(canonical);box.textContent='视频已保存在云管家，当前版本已关联。审核状态沿用原业务记录。';success=true;}
   catch(error){showError(error.message);box.textContent='原文件选择和上传会话已保留。继续时先读取原分片与素材记录。';}
   finally{busy(false);pause.hidden=true;resume.hidden=success;videoAbort=null;}
  }
  $('#delivery-video')?.addEventListener('change',e=>{if(uploading)return;selectedVideo=e.target.files[0];$('#delivery-video-resume').hidden=!selectedVideo;if(selectedVideo)void continueVideo();});
  $('#delivery-video-resume')?.addEventListener('click',()=>void continueVideo());
  $('#delivery-video-pause')?.addEventListener('click',()=>videoAbort?.abort());
 }
 selected();showExisting();queueHtml();
 form.onsubmit=async e=>{e.preventDefault();if(uploading||form.dataset.busy==='true')return;showError('');try{const note=form.querySelector('[name=note]').value.trim();if(!note)throw Error('请写明本次'+(reuse?'确认结论':'交付说明')+'。');let evidence=[];if(!reuse){evidence=[...draft.selected.values()].map(deliverySelectionRef);const links=(draft.links||'').split(/\n/).map(s=>s.trim()).filter(Boolean);for(const url of links){let parsed;try{parsed=new URL(url);}catch{}if(!parsed||!['http:','https:'].includes(parsed.protocol))throw Error('交付链接必须是有效的 http 或 https 地址。');evidence.push({url,summary:note});}if(!evidence.length)throw Error('请上传或选择交付物，也可以提供一条交付链接。');if(evidence.length>12)throw Error('一次最多选用 12 项交付，请精简本次选择。');}const body={expectedVersion:task.version,nodeId:node.id,note,evidence},current=JSON.stringify(body);if(current!==signature){signature=current;keyForSubmit=crypto.randomUUID();}busy(true);const result=await api('runs/'+task.id+'/complete',{body,key:keyForSubmit});busy(false);deliveryDrafts.delete(key);$('#modal').close();state.task=result;renderTask();toast(reuse?'确认已保存，流程继续推进。':'交付已保存，可在任务中核对下一主责和通知回执。');await refresh();}catch(error){showError(error.message+' 当前交付和说明已保留。');}finally{busy(false);}};
}
