import test from 'node:test';import assert from 'node:assert/strict';import vm from 'node:vm';import {readFileSync} from 'node:fs';
const source=readFileSync(new URL('app.js',import.meta.url),'utf8');
const functions=source.slice(source.indexOf('function canStartDownstreamNow('),source.indexOf('\nasync function openWatch('));
const open=source.slice(source.indexOf('async function openHandoff('),source.indexOf('\nfunction showModal('));
const task=()=>({id:'task_parent',workflow:'05',title:'真实事项',acceptance:'凭证可核验',version:9,assignee:{number:'A'},runtime:{state:'running',manager:{number:'M'},nodes:[{id:'before',state:'completed',dependencies:[]},{id:'W05.S5.E1',state:'ready',dependencies:['before']}]}});
function fixture(t=task()){const calls={};const state={task:t,overview:{access:{canManage:true}},catalog:{edges:[['05','01','新制作行动']],flows:[{id:'01'}]}};const context=vm.createContext({state,esc:x=>String(x??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;'),flowName:x=>'流程'+x,personalRelationsHtml:()=>'<div>我的上下游</div>',api:async()=>({items:[]}),showModal:(...args)=>calls.modal=args,setupSubmit:(...args)=>calls.submit=args,toast:x=>calls.toast=x,refresh:async()=>{},renderTask:()=>{},options:()=>'',peopleOptions:()=>'',field:()=>''});vm.runInContext(functions+'\n'+open,context);return {context,state,calls};}
test('只有激活第9节点管理视图显示现在发起，同时保留完成后默认',()=>{const f=fixture();let html=f.context.handoffHtml(f.state.task);assert.match(html,/现在发起下游/);assert.match(html,/设置完成后交接/);f.state.task.runtime.nodes[0].state='pending';assert.doesNotMatch(f.context.handoffHtml(f.state.task),/现在发起下游/);});
test('普通同事只看原上下游，不得到立即交接控制',()=>{const f=fixture();f.state.overview.access.canManage=false;assert.equal(f.context.handoffHtml(f.state.task),'<div>我的上下游</div>');});
test('已创建下游只显示原编号和打开按钮，不重复提供创建',()=>{const f=fixture();f.state.task.runtime.handoff={state:'dispatched',dispatchMode:'now',taskId:'task_child'};const html=f.context.handoffHtml(f.state.task);assert.match(html,/<code>task_child<\/code>/);assert.match(html,/父流程继续按原节点办理/);assert.doesNotMatch(html,/data-handoff=/);});
test('下游编号仍进行HTML转义',()=>{const f=fixture();f.state.task.runtime.handoff={state:'dispatched',taskId:'<script>unsafe</script>'};const html=f.context.handoffHtml(f.state.task);assert.doesNotMatch(html,/<script>/);assert.match(html,/&lt;script&gt;/);});
test('立即弹窗明确现在创建，提交原handoff接口且带显式now',async()=>{const f=fixture();await f.context.openHandoff('now');assert.equal(f.calls.modal[0],'现在发起下游');assert.equal(f.calls.modal[3],'创建下游任务');const values={workflow:'01',title:'下游',acceptance:'交付',owner:'A',manager:'M',slaHours:'24',production:'ai'};const b=f.calls.submit[0]({get:k=>values[k]});assert.equal(b.dispatchMode,'now');assert.equal(b.expectedVersion,9);assert.equal(b.workflow,'01');});
test('默认弹窗维持完成后交接，状态变化不弹现在创建',async()=>{const f=fixture();await f.context.openHandoff();assert.equal(f.calls.modal[0],'设置完成后自动交接');const b=f.calls.submit[0]({get:()=>''});assert.equal(b.dispatchMode,undefined);delete f.calls.modal;f.state.task.runtime.state='paused';await f.context.openHandoff('now');assert.equal(f.calls.modal,undefined);assert.match(f.calls.toast,/状态已变化/);});
test('交接表单显示当前已发布制作分支，不提供会被后台忽略的选择',async()=>{
 const f=fixture();f.context.api=async path=>path==='blueprints'?{active:{version:9,moduleOrder:['01'],modules:{'01':{options:{production:'shoot'}}}}}:{items:[]};
 await f.context.openHandoff();assert.match(f.calls.modal[2],/name="production" disabled/);assert.match(f.calls.modal[2],/已发布 v9/);assert.match(f.calls.modal[2],/制作方式为实拍/);
 const body=f.calls.submit[0]({get:name=>name==='workflow'?'01':name==='production'?'ai':''});assert.equal(body.options.production,'shoot');
});
