import type { AppModule } from "./types";

const hubBasePath = String(import.meta.env.VITE_HUB_PUBLIC_BASE_PATH || "/yxb/wis-marketing-hub/")
  .replace(/\/+$/u, "");
const modulePath = (path: string) => `${hubBasePath}/modules/${path}`;

export const modules: AppModule[] = [
  {
    id: "data-dashboard",
    index: "01",
    title: "根数据看板",
    kicker: "先看整体经营情况",
    description: "集中查看抖音及关联渠道的经营结果、利润趋势、目标进度和单品表现。",
    purpose: "经营情况总览",
    tone: "violet",
    status: "online",
    actionLabel: "进入系统",
    url: modulePath("data-dashboard/"),
    features: [
      { title: "经营总览", description: "查看全渠道经营结果和目标完成情况" },
      { title: "单品与利润", description: "查看单品表现、利润变化和趋势" },
      { title: "结果复盘", description: "汇总素材投放和直播经营结果" },
    ],
  },
  {
    id: "creative-hub",
    index: "02",
    title: "创意工作台",
    kicker: "先确定创意从哪里来",
    description: "统一进入 Idea OS、创意中枢平台和 IP Kanban，贯通灵感构思、创意生产投放复盘与 IP 项目管理。",
    purpose: "创意来源",
    tone: "violet",
    status: "online",
    actionLabel: "进入系统",
    url: modulePath("creative-hub/"),
    features: [
      { title: "Idea OS 创意系统", description: "捕捉灵感、梳理想法并形成清晰创意方案" },
      { title: "创意中枢平台", description: "贯通创意生产、投放追踪与复盘闭环" },
      { title: "IP Kanban 管理看板", description: "集中管理 IP 项目、执行进度和内容节奏" },
    ],
  },
  {
    id: "ai-first-creation",
    index: "03",
    title: "AI一创工作台",
    kicker: "把创意方向做成原创内容",
    description: "根据创意方向和产品资料，完成原创脚本、镜头规划、产品展示与母版成片。",
    purpose: "一创创作",
    tone: "teal",
    status: "online",
    actionLabel: "进入系统",
    url: modulePath("ai-first-creation/"),
    features: [
      { title: "原创与产品展示", description: "自动化 Allive、KOC 桌拍和产品镜制作" },
      { title: "替换与裂变", description: "完成产品替换、背景替换和竞对视频复刻" },
      { title: "提示词逆推", description: "从参考视频提炼母提示词与逐镜提示词" },
    ],
  },
  {
    id: "material-workbench",
    index: "04",
    title: "WIS素材工作台",
    kicker: "用现有素材完成二创混剪",
    description: "从素材中心选材、切片和编排，完成批量混剪、审核与成片回传。",
    purpose: "二创混剪",
    tone: "amber",
    status: "beta",
    actionLabel: "进入系统",
    url: modulePath("material-workbench/"),
    features: [
      { title: "选材与切片", description: "从素材库选片并整理可复用片段" },
      { title: "框架编排", description: "按照内容结构组合文案、镜头和片段" },
      { title: "批量混剪", description: "生成多个成片版本并提交审核回传" },
    ],
  },
  {
    id: "cloud-manager",
    index: "05",
    title: "WIS云管家",
    kicker: "统一存储、推送和回流",
    description: "集中管理一创、二创和直播素材，完成审核入库、渠道推送与表现回流。",
    purpose: "WIS云管家",
    tone: "teal",
    status: "online",
    actionLabel: "进入系统",
    url: modulePath("cloud-manager/"),
    features: [
      { title: "素材主库", description: "统一保存视频、图片、切片和成片版本" },
      { title: "审核与推送", description: "审核素材并推送到对应渠道和账户" },
      { title: "表现回流", description: "回收素材使用情况和渠道表现数据" },
    ],
  },
  {
    id: "live-room-management",
    index: "06",
    title: "直播间",
    kicker: "直播排班与现场管理",
    description: "直播首页、数据中心和调度中心已接入隔离候选；历史人工记录仍待恢复，正式办理需通过本人及岗位验收。",
    purpose: "直播间",
    tone: "amber",
    status: "beta",
    actionLabel: "查看直播工作台",
    url: modulePath("live-room-management/"),
    features: [
      { title: "直播首页", description: "查看直播间、值班与状态" },
      { title: "数据中心", description: "核对场次与经营数据的真实来源" },
      { title: "调度中心", description: "只读查看已核验的排班备份，历史待恢复" },
    ],
  },
];
