export type SparkStatus = 'draft' | 'published' | 'implemented' | 'failed';
export type SparkScoreKey = 'business' | 'execution' | 'evidence' | 'reuse';
export type SparkSource = {
  id: string;
  type?: string;
  name?: string;
  channel?: string;
  author?: string;
  date?: string;
  quote?: string;
  url?: string;
  location?: string;
  locator?: string;
  limitations?: string | string[];
  limitation?: string;
  center?: string;
};
export type SparkActor = string | { number?: string; name?: string; realName?: string; role?: string };
export type SparkHistory = { from?: string | null; to: string; at?: string; note?: string; by?: SparkActor; actor?: SparkActor };
export type SparkItem = {
  id: string;
  title: string;
  summary?: string;
  category?: string;
  center?: string;
  date?: string;
  createdAt?: string;
  status: SparkStatus;
  sourceIds: string[];
  evidence?: string;
  insight?: string;
  action?: string;
  validation?: string;
  scoreDimensions?: Partial<Record<SparkScoreKey, number>>;
  scoreReasons?: Partial<Record<SparkScoreKey, string>>;
  statusEvidence?: string;
  statusHistory?: SparkHistory[];
  version: number;
  updatedAt?: string;
  updatedBy?: SparkActor;
  [key: string]: unknown;
};
export type SparkRun = {
  id?: string;
  status?: string;
  startedAt?: string;
  finishedAt?: string;
  at?: string;
  summary?: string;
  error?: string;
  added?: number;
  updated?: number;
  [key: string]: unknown;
};
export type SparkOverview = {
  ok: boolean;
  revision: number;
  items: SparkItem[];
  sources: SparkSource[];
  coverage?: Record<string, unknown>;
  runs?: SparkRun[];
  access?: { canEdit: boolean };
  updatedAt?: string;
  lastSuccessfulAt?: string | null;
};
